// Mocks generated by Mockito 5.4.6 from annotations
// in test_task_113/test/data/repositories/order_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_task_113/data/datasources/remote/models/order_dto.dart'
    as _i3;
import 'package:test_task_113/data/datasources/remote/order_remote_data_source.dart'
    as _i5;
import 'package:test_task_113/data/mappers/order_mapper.dart' as _i7;
import 'package:test_task_113/domain/entities/order.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderDto_1 extends _i1.SmartFake implements _i3.OrderDto {
  _FakeOrderDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrder_2 extends _i1.SmartFake implements _i4.Order {
  _FakeOrder_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRemoteDataSource extends _i1.Mock
    implements _i5.OrderRemoteDataSource {
  MockOrderRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i6.Future<_i3.OrderDto> createOrder(int? userId, int? serviceId) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [userId, serviceId]),
            returnValue: _i6.Future<_i3.OrderDto>.value(
              _FakeOrderDto_1(
                this,
                Invocation.method(#createOrder, [userId, serviceId]),
              ),
            ),
          )
          as _i6.Future<_i3.OrderDto>);
}

/// A class which mocks [OrderMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderMapper extends _i1.Mock implements _i7.OrderMapper {
  MockOrderMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Order toEntity(_i3.OrderDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#toEntity, [dto]),
            returnValue: _FakeOrder_2(
              this,
              Invocation.method(#toEntity, [dto]),
            ),
          )
          as _i4.Order);

  @override
  _i3.OrderDto toDto(_i4.Order? entity) =>
      (super.noSuchMethod(
            Invocation.method(#toDto, [entity]),
            returnValue: _FakeOrderDto_1(
              this,
              Invocation.method(#toDto, [entity]),
            ),
          )
          as _i3.OrderDto);
}
